### ISSUE TITLE
PHP: Missing Closing Script Mark

### ISSUE THREAD

**Issue by fr33roam3r** [DanWin/le-chat-php#83] opened 2020-09-15 09:52 UTC
It appears that there's a minor typo in the PHP scripts for this project: Though all the scripts start with `<?php`, it does not end with `?>`. It's a simple fix, and I would be glad to do the work for a pull request, if this is significant enough to matter.

**Comment by DanWin** [comment] 2020-09-15 10:04
It's not a bug, it's a feature. It prevents outputting unnecessary whitespace and potential issues related to that. See also: https://www.php.net/basic-syntax.instruction-separation
In general it's good practice not to use the closing php tag at the end of a php script.

**Closed by DanWin** 2020-09-15 10:04 UTC
